/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api.users'
import { Route as ApiUsageLogRouteImport } from './routes/api.usage-log'
import { Route as ApiMeRouteImport } from './routes/api.me'
import { Route as ApiGenerateAdsRouteImport } from './routes/api.generate-ads'
import { Route as ApiExtractRouteImport } from './routes/api.extract'
import { Route as ApiBrandProfileRouteImport } from './routes/api.brand-profile'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ApiUsersIdRouteImport } from './routes/api.users.$id'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAdsIdRouteImport } from './routes/api.ads.$id'
import { Route as ApiAdsIdRegenerateRouteImport } from './routes/api.ads.$id.regenerate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageLogRoute = ApiUsageLogRouteImport.update({
  id: '/api/usage-log',
  path: '/api/usage-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAdsRoute = ApiGenerateAdsRouteImport.update({
  id: '/api/generate-ads',
  path: '/api/generate-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandProfileRoute = ApiBrandProfileRouteImport.update({
  id: '/api/brand-profile',
  path: '/api/brand-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsIdRoute = ApiAdsIdRouteImport.update({
  id: '/api/ads/$id',
  path: '/api/ads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsIdRegenerateRoute = ApiAdsIdRegenerateRouteImport.update({
  id: '/regenerate',
  path: '/regenerate',
  getParentRoute: () => ApiAdsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/generate-ads': typeof ApiGenerateAdsRoute
  '/api/me': typeof ApiMeRoute
  '/api/usage-log': typeof ApiUsageLogRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/ads/$id': typeof ApiAdsIdRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/ads/$id/regenerate': typeof ApiAdsIdRegenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/generate-ads': typeof ApiGenerateAdsRoute
  '/api/me': typeof ApiMeRoute
  '/api/usage-log': typeof ApiUsageLogRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/ads/$id': typeof ApiAdsIdRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/ads/$id/regenerate': typeof ApiAdsIdRegenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/generate-ads': typeof ApiGenerateAdsRoute
  '/api/me': typeof ApiMeRoute
  '/api/usage-log': typeof ApiUsageLogRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/ads/$id': typeof ApiAdsIdRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/ads/$id/regenerate': typeof ApiAdsIdRegenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create'
    | '/login'
    | '/admin/login'
    | '/api/brand-profile'
    | '/api/extract'
    | '/api/generate-ads'
    | '/api/me'
    | '/api/usage-log'
    | '/api/users'
    | '/api/ads/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/users/$id'
    | '/api/ads/$id/regenerate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/create'
    | '/login'
    | '/admin/login'
    | '/api/brand-profile'
    | '/api/extract'
    | '/api/generate-ads'
    | '/api/me'
    | '/api/usage-log'
    | '/api/users'
    | '/api/ads/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/users/$id'
    | '/api/ads/$id/regenerate'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/create'
    | '/login'
    | '/admin_/login'
    | '/api/brand-profile'
    | '/api/extract'
    | '/api/generate-ads'
    | '/api/me'
    | '/api/usage-log'
    | '/api/users'
    | '/api/ads/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/users/$id'
    | '/api/ads/$id/regenerate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiBrandProfileRoute: typeof ApiBrandProfileRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiGenerateAdsRoute: typeof ApiGenerateAdsRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiUsageLogRoute: typeof ApiUsageLogRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAdsIdRoute: typeof ApiAdsIdRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage-log': {
      id: '/api/usage-log'
      path: '/api/usage-log'
      fullPath: '/api/usage-log'
      preLoaderRoute: typeof ApiUsageLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-ads': {
      id: '/api/generate-ads'
      path: '/api/generate-ads'
      fullPath: '/api/generate-ads'
      preLoaderRoute: typeof ApiGenerateAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-profile': {
      id: '/api/brand-profile'
      path: '/api/brand-profile'
      fullPath: '/api/brand-profile'
      preLoaderRoute: typeof ApiBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/$id': {
      id: '/api/ads/$id'
      path: '/api/ads/$id'
      fullPath: '/api/ads/$id'
      preLoaderRoute: typeof ApiAdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/$id/regenerate': {
      id: '/api/ads/$id/regenerate'
      path: '/regenerate'
      fullPath: '/api/ads/$id/regenerate'
      preLoaderRoute: typeof ApiAdsIdRegenerateRouteImport
      parentRoute: typeof ApiAdsIdRoute
    }
  }
}

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiAdsIdRouteChildren {
  ApiAdsIdRegenerateRoute: typeof ApiAdsIdRegenerateRoute
}

const ApiAdsIdRouteChildren: ApiAdsIdRouteChildren = {
  ApiAdsIdRegenerateRoute: ApiAdsIdRegenerateRoute,
}

const ApiAdsIdRouteWithChildren = ApiAdsIdRoute._addFileChildren(
  ApiAdsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiBrandProfileRoute: ApiBrandProfileRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiGenerateAdsRoute: ApiGenerateAdsRoute,
  ApiMeRoute: ApiMeRoute,
  ApiUsageLogRoute: ApiUsageLogRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAdsIdRoute: ApiAdsIdRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
